In [2]:
import numpy as np

In [15]:

a= np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


In [5]:
#get specific element
a[1,5]

13

In [6]:
# get specific row
a[0, :]

array([1, 2, 3, 4, 5, 6, 7])

In [7]:
# specific column
a[:, 1]

array([2, 9])

In [9]:
# getting a little fancy [start index: end index: stepsize]
a[0, 0:6:2]
a[1, 2:8: 3]

array([10, 13])

In [10]:
a[1,5] = 20
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 20 14]]


In [12]:
a[:,2] = 5
a[:, 2] = [1,2]
print(a)

[[ 1  2  1  4  5  6  7]
 [ 8  9  2 11 12 20 14]]


In [3]:
b = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(b)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [4]:
# initializing different types of arrays

#all zero matrix
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [6]:
#all 1's matrix
np.ones((4,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [9]:
np.ones((4,3,4))

array([[[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]]])

In [12]:
#any other number
np.full((2,2),26)

array([[26, 26],
       [26, 26]])

In [16]:
np.full_like(a,47)

array([[47, 47, 47, 47, 47, 47, 47],
       [47, 47, 47, 47, 47, 47, 47]])

In [17]:
np.random.rand(4,2)

array([[0.83172518, 0.0179133 ],
       [0.23208871, 0.75624352],
       [0.08357569, 0.08122803],
       [0.78110974, 0.54042882]])

In [20]:
np.random.random_sample(a.shape)

array([[0.76094934, 0.19651655, 0.93463164, 0.32043219, 0.98852118,
        0.02181702, 0.51972528],
       [0.32051236, 0.94224921, 0.68702586, 0.43549395, 0.59394035,
        0.28263564, 0.0475589 ]])

In [21]:
#Random integer values
np.random.randint(4,8, size=(3,3))   # the upper value is exclusive.... ex 8 here

array([[5, 5, 6],
       [4, 7, 4],
       [7, 7, 7]])

In [26]:
# The identity matrix
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [25]:
# Repeat an array
array = np.array([[1,2,3,4]])
r1 = np.repeat(array,3, axis = 0)
print(r1)

[[1 2 3 4]
 [1 2 3 4]
 [1 2 3 4]]


In [31]:
output = np.ones((5,5))
print(output)

z = np.zeros((3,3))
z[1,1] = 9
print(z)

output[1:4,1:4] = z
print(output)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[[0. 0. 0.]
 [0. 9. 0.]
 [0. 0. 0.]]
[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 9. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


##### Be careful when copying arrays

In [6]:
a = np.array([1,2,3])
b = a
b[0] = 100
print(b)
print(a)

[100   2   3]
[100   2   3]


##### here the value is saved in a[0] as well


In [8]:
a= np.array([1,2,3])
b= a.copy()
b[0] = 100
print(b)
print(a)

[100   2   3]
[1 2 3]


##### Mathematics

In [9]:
a = np.array([1,2,3,4])
print(a)

[1 2 3 4]


In [10]:
a+2

array([3, 4, 5, 6])

In [11]:
b = np.array([1,0,1,0])
a+b

array([2, 2, 4, 4])

In [12]:
a**2

array([ 1,  4,  9, 16], dtype=int32)

In [13]:
np.sin(a)

array([ 0.84147098,  0.90929743,  0.14112001, -0.7568025 ])

##### linear algebra

In [14]:
a = np.ones((2,3))
print(a)

[[1. 1. 1.]
 [1. 1. 1.]]


In [15]:
b = np.full((3,2),2)
print(b)

[[2 2]
 [2 2]
 [2 2]]


In [17]:
np.matmul(a,b)

array([[6., 6.],
       [6., 6.]])

In [19]:
# find determinant
a = np.identity(3)
np.linalg.det(a)

1.0

##### statistics


In [20]:
stats = np.array([[1,2,3],[4,5,6]])
stats

array([[1, 2, 3],
       [4, 5, 6]])

In [21]:
np.min(stats)

1

In [22]:
np.max(stats)

6

In [23]:
np.min(stats, axis=1)

array([1, 4])

In [31]:
np.sum(stats,axis =0)

array([5, 7, 9])

In [32]:
np.sum(stats,axis =1)

array([ 6, 15])

##### Reorganizing Arrays

In [43]:
before = np.array([[1,2,3,4],[5,6,7,8]])
before
after = before.reshape((4,2))
after

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [44]:
#vertical stack
v1 = np.array([1,2,3,4])
v2 = np.array([5,6,7,8])
np.vstack([v1,v2,v1,v2])

array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [1, 2, 3, 4],
       [5, 6, 7, 8]])

#horizontal stack
v1 = np.array([1,2,3,4])
v2 = np.array([5,6,7,8])
np.hstack((v1,v2))

##### Miscellaneous
Load Data from File